### ISSUE TITLE
Blank red box appears when plugin is used

### ISSUE THREAD

**Issue by 3mikey1** [Sadret/openrct2-price-manager#1]
![2021-11-29 (2)](https://user-images.githubusercontent.com/95266304/143982961-935dd27c-24b8-43ce-933d-b2a3addd6cec.png)

When this plugin is in the plugin folder (confirmed only happens when this one specifically is), a blank red box as shown frequently appears on screen.

**Comment by Sadret** [comment]
The red box is an error box from RCT, but it's missing any error message. Apparently something went wrong but RCT does not really know how to handle it. This said, I don't know what the problem is.

Can you provide more information, please? E.g.
- Are you on develop or release branch?
- Does it appear with certain rides/shops only?
- How often does it appear?
- Does it only appear when it rains?

Maybe you can attach a save file where it is happening.
